### ISSUE TITLE
Deleting a file attached to an item deletes the item

### ISSUE THREAD

**Issue by LandazuriPaul** [directus/api#1508]
# Bug report

With a collection having a field of the **File** type, if, while updating an item from the collection, we want to **delete** (and not to deselect) the file from the File interface, it also deletes the item!

## Behaviour expected

When we just want to delete a file attached to any collection item, it shouldn't remove the item, but just the targeted file.

## Reproduction

You can reproduce the bug in the demo app. I have created a  collection named [File Attached](https://demo.directus.io/admin/#/thumper/collections/file_attached) for this purpose.

## Observations

Actually, as it happened to me several times, I noticed that whenever this happens, the deleted item is still present but broken in the database. The bug is that **the value of the file field isn't updated**. So the item still points to a file that doesn't exist anymore, and that's the reason why we can't find it in the collection anymore. By updating the corresponding field in the database to the *NULL* value, we can have our item back. It clearly denotes a bug in the file deletion process which, after having deleted the file, doesn't update the corresponding item. And hopefully, it has a simple fix.

---
Directus version: 8.0.x
(I hadn't experienced this bug in 7.x)

**Comment by rijkvanzanten** [comment]
@bjgajjar The API returns an empty array for all data as soon as there's one relational item to directus files that doesn't exist anymore.

For example, in a table with a text-input and a file, it will return

```json
{
  "data": []
}
```

instead of

```json
{
  "data": {
    "text-input": "My value",
    "file": null
  }
}
```

if file is set to a non-existing primary key

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1512

**Comment by LandazuriPaul** [comment]
Thank you @bjgajjar for the quick fix!

Do you have any idea regarding when it will be merged into the https://github.com/directus/directus master branch?

**Comment by rijkvanzanten** [comment]
@LandazuriPaul this week!

**Comment by jimmycrackc0rn7** [comment]
Any update?  I am still experiencing this bug on v8.4.0.  Same steps to reproduce.

**Comment by rijkvanzanten** [comment]
@bjgajjar could you verify this?

**Comment by sneakersgames** [comment]
Same here on version 8.3.1

**Comment by hemratna** [comment]
@sneakersgames @jimmycrackc0rn7 
I verify the same Directus demo and it's working fine. 
Can you please update the Directus to 8.5.4 and check again?
